### ISSUE TITLE
`get_hist_transition_matrix` Returning Negative Values

### ISSUE THREAD

**Issue by IsaccBarker** [UofUEpiBio/epiworld#21]
```python
grouped = transition_matrix.groupby(['dates', 'states_to'])['counts'].sum().unstack().fillna(0)
daily_incidence = grouped.diff().fillna(0)

# Plot!
plt.figure(figsize=(10, 6))
plt.plot(daily_incidence.index, daily_incidence['Infected'], label='New Infected')
plt.plot(daily_incidence.index, daily_incidence['Recovered'], label='New Recovered')

plt.title('Daily Incidence of Infected and Recovered Cases')
plt.xlabel('Days')
plt.ylabel('Number of New Cases')
plt.legend()
plt.grid(True)
plt.show()
```

![image](https://github.com/user-attachments/assets/e2021cb4-1fbf-4bd0-9795-cf2aa44e4b64)

**Comment by gvegayon** [comment]
False alarm here; there's no bug (see the tagged PR). Nonetheless, there should be a fix about how to deal with missing values. For the moment, epiworld assigns a -1 integer to individuals with no generation time; which should be treated as missing. @apulsipher, can you create an issue to address this? Title: "Explore how to return consistent missing values in C++ (instead of -1)."

**Comment by gvegayon** [comment]
https://github.com/EpiForeSITE/epiworld-milo-talk/pull/2
